// Données des projets du showcase — source unique pour le carousel 3D et
// la vue détaillée. Contenus, images et liens existants conservés à
// l'identique ; enrichis de `views` : les différentes vues du projet
// (multi-angle), chacune avec sa légende — le carousel raconte le projet.

export const PROJECTS = [
  {
    n: '01',
    tag: 'Projet de référence',
    title: 'LUMO',
    role: 'Conçu et développé de A à Z',
    image: '/lumo/screen1.png',
    alt: 'Interface LUMO — mouvements de stock',
    href: '#lumo',
    cta: "Voir l'étude de cas",
    external: false,
    stack: ['React', 'Node.js', 'PostgreSQL'],
    context: 'Les petits commerces suivaient ventes et stocks sur des cahiers.',
    problem: 'Aucune visibilité sur les entrées, sorties et niveaux de stock au quotidien.',
    result: 'Une plateforme de gestion commerciale centralisée, déployée en production.',
    scope: ['Ventes & caisse', 'Achats', 'Stocks & produits', 'Clients & fournisseurs', 'Rôles (RBAC)', 'Tableau de bord'],
    views: [
      {
        src: '/lumo/screen1.png',
        label: 'Mouvements de stock',
        note: 'Traçabilité entrées / sorties, recherche et filtres',
        fit: 'contain',
      },
      {
        src: '/lumo/screen2.png',
        label: 'Produits & stocks',
        note: 'Catalogue, niveaux de stock et alertes',
        fit: 'contain',
      },
      {
        src: '/lumo/screen3.png',
        label: 'Tableau de bord',
        note: "Les indicateurs clés de l'activité en un coup d'œil",
        fit: 'contain',
      },
      {
        src: '/lumo/screen5.png',
        label: 'Caisse (POS)',
        note: 'Le panier client et la finalisation de la vente',
        fit: 'contain',
      },
      {
        src: '/lumo/screen4.png',
        label: 'Interface responsive',
        note: 'Pensée mobile et bureau',
        fit: 'contain',
      },
    ],
  },
  {
    n: '02',
    tag: 'Plateforme touristique',
    title: 'Visit.toi',
    role: 'Conçu et développé de A à Z · Design & motion',
    image: '/visit-toi/cover.svg',
    alt: 'Visit.toi — plateforme touristique communautaire pour la RDC',
    href: '#contact',
    cta: 'Discuter de ce projet',
    external: false,
    stack: ['React', 'TypeORM', 'PostgreSQL', 'Mapbox'],
    context: 'Découvrir les lieux et merveilles de la RDC, sans données fiables ni interface soignée.',
    problem: 'Informations dispersées et peu fiables sur les sites touristiques du pays.',
    result: 'Une plateforme communautaire : carte interactive, favoris, avis, profils et console de modération.',
    scope: ['Carte interactive', 'Favoris', 'Avis', 'Profils', 'Console de modération'],
    views: [
      {
        src: '/visit-toi/cover.png',
        label: 'Vue d’ensemble',
        note: 'Plateforme touristique communautaire pour la RDC',
        fit: 'cover',
      },
      {
        src: '/visit-toi/mobile.png',
        label: 'Interface mobile',
        note: 'Découverte pensée mobile — Explorer, Avis, Favoris',
        fit: 'contain',
      },
    ],
  },
  {
    n: '03',
    tag: 'Génération de CV',
    title: 'CV Studio',
    role: 'Design & code · Génération de CV',
    image: '/cvstudio/screen1.png',
    alt: 'CV Studio — générateur de CV professionnel en ligne',
    href: 'https://cv-studio-jade.vercel.app/',
    cta: 'Voir le site live',
    external: true,
    stack: ['React', 'Tailwind', 'Vercel'],
    context: 'Créer un CV professionnel moderne, sans outil payant ni gabarit rigide.',
    problem: 'Des CV génériques, coûteux à produire, difficilement personnalisables.',
    result: 'Un studio en ligne pour composer et exporter des CV soignés — en production.',
    scope: ['Éditeur de contenu', 'Modèles', 'Export PDF', 'Publication'],
    views: [
      {
        src: '/cvstudio/screen1.png',
        label: 'Vue d’ensemble',
        note: 'Générateur de CV professionnel en ligne',
        fit: 'contain',
      },
    ],
  },
  {
    n: '04',
    tag: 'Projet réel',
    title: 'Ce portfolio',
    role: 'Design & code · Motion · Frontend',
    image: '/portfolio-cover.png',
    alt: 'René Descartes — portfolio, image de marque',
    href: '#contact',
    cta: 'Créer un projet similaire',
    external: false,
    stack: ['React', 'Vite', 'Motion'],
    context: "Comment montrer un travail sérieux, sans ressembler à un site tout fait ?",
    problem: 'Un portfolio efficace doit montrer le design ET le code, sans gabarit.',
    result: "Un site conçu à la main : traînée fluide au curseur, motion design, thème clair/sombre.",
    scope: ['Design éditorial', 'Motion design', 'Thème clair/sombre', 'Backend contact'],
    views: [
      {
        src: '/portfolio-cover.png',
        label: 'Image de marque',
        note: 'Portfolio conçu à la main — design éditorial et motion',
        fit: 'cover',
      },
    ],
  },
]
